### ISSUE TITLE
Raspberry PI

### ISSUE THREAD

**Issue by luisfavila** [ipilcher/fdf#4]
Hi,

Pardon my (probably) stupid question, but I'd like to have a clear answer before I dive into compiling and running this: would this theoretically work on a RPI4 connected to multiple networks (vlans)? I use OpenWRT but would rather not run it directly there as it just adds more complexity. Unfortunately, running avahi on my openwrt router doesn't seem to be enough to get chromecast/nest minis working across networks.

Thanks

**Comment by ipilcher** [comment]
It should be possible to run this on a Rasberry Pi 4.  In fact, it should be easier to get it working than it was on OpenWrt, as it's significantly more powerful than most routers, and should have a much more "full fledged" Linux distribution.

That said, I have absolutely no experience with the platform, so I'm not sure how much I'll be able to help.  If you have experience building software for the platform, and the distribution provides the required libraries, it shouldn't be terribly difficult.  If not, it could be a nightmare.
